import type { DesignPreset } from './designTypes';

export const DEFAULT_DESIGN_PRESET = {
  id: 'default-v1',
  name: 'Diseno actual protegido',
  protected: true,
  version: 1,
  texts: {
    dashboardTitle: 'Visor de Facturacion y Reclamos - RM/Regiones',
    dashboardSubtitle: 'Inteligencia operativa para decisiones estrategicas',
  },
  tokens: {
    primaryColor: 'default',
    backgroundColor: 'default',
    cardColor: 'default',
    textColor: 'default',
    borderRadius: 'default',
    spacingMode: 'comfortable',
  },
  sections: [
    { id: 'hero', label: 'Indicadores principales', visible: true, order: 0 },
    { id: 'main', label: 'Mapa principal', visible: true, order: 1 },
    { id: 'side', label: 'Resumen operativo', visible: true, order: 2 },
    { id: 'bottom', label: 'Analisis y evidencia', visible: true, order: 3 },
  ],
  widgets: [
    { id: 'kpiFacturacion', title: 'Facturacion total', description: 'Monto total del periodo seleccionado.', visible: true, order: 0, section: 'hero', size: 'medium' },
    { id: 'kpiReclamos', title: 'Reclamos totales', description: 'Total de reclamos filtrados.', visible: true, order: 1, section: 'hero', size: 'medium' },
    { id: 'kpiPromedio', title: 'Promedio por reclamo', description: 'Facturacion promedio por reclamo.', visible: true, order: 2, section: 'hero', size: 'medium' },
    { id: 'mapaReclamos', title: 'Mapa de reclamos', description: 'Intensidad territorial de reclamos.', visible: true, order: 0, section: 'main', size: 'large' },
    { id: 'kpiComunaTop', title: 'Top reclamos', description: 'Comuna con mayor cantidad de reclamos.', visible: true, order: 0, section: 'side', size: 'medium' },
    { id: 'kpiFacturacionTop', title: 'Top facturacion', description: 'Comuna con mayor facturacion.', visible: true, order: 1, section: 'side', size: 'medium' },
    { id: 'kpiCoberturaComunas', title: 'Cobertura', description: 'Comunas con informacion disponible.', visible: true, order: 2, section: 'side', size: 'medium' },
    { id: 'statTotalComunas', title: 'Total comunas', description: 'Cantidad de comunas filtradas.', visible: true, order: 0, section: 'bottom', size: 'small' },
    { id: 'statAltaPrioridad', title: 'Alta prioridad', description: 'Reclamos de prioridad alta.', visible: true, order: 1, section: 'bottom', size: 'small' },
    { id: 'statVariacionMensual', title: 'Periodo analizado', description: 'Periodo aplicado a datos actuales.', visible: true, order: 2, section: 'bottom', size: 'small' },
    { id: 'statTicketsUnicos', title: 'Tickets unicos', description: 'Tickets distintos en el periodo.', visible: true, order: 3, section: 'bottom', size: 'small' },
    { id: 'graficoFacturacionMensual', title: 'Facturacion mensual', description: 'Evolucion mensual de facturacion.', visible: true, order: 4, section: 'bottom', size: 'medium' },
    { id: 'topComunasReclamos', title: 'Top 10 comunas con mas reclamos', description: 'Ranking por volumen de reclamos.', visible: true, order: 5, section: 'bottom', size: 'medium' },
    { id: 'topComunasFacturacion', title: 'Top 10 comunas con mayor facturacion', description: 'Ranking por facturacion.', visible: true, order: 6, section: 'bottom', size: 'medium' },
    { id: 'distribucionPrioridad', title: 'Distribucion por prioridad', description: 'Composicion por prioridad.', visible: true, order: 7, section: 'bottom', size: 'medium' },
    { id: 'tablaComunas', title: 'Evidencia por comuna', description: 'Tabla de respaldo operacional.', visible: true, order: 8, section: 'bottom', size: 'large' },
  ],
  kpis: [
    { id: 'kpiFacturacion', title: 'Facturacion total', description: 'Monto total del periodo seleccionado.', icon: 'file', accent: 'blue', visible: true, order: 0, section: 'hero', size: 'medium', protected: true, source: 'dashboard_resumen', field: 'facturacion_total', aggregation: 'sum', datasetScope: 'all' },
    { id: 'kpiReclamos', title: 'Reclamos totales', description: 'Total de reclamos filtrados.', icon: 'alert', accent: 'red', visible: true, order: 1, section: 'hero', size: 'medium', protected: true, source: 'dashboard_resumen', field: 'reclamos_totales', aggregation: 'sum', datasetScope: 'all' },
    { id: 'kpiPromedio', title: 'Promedio por reclamo', description: 'Facturacion promedio por reclamo.', icon: 'users', accent: 'cyan', visible: true, order: 2, section: 'hero', size: 'medium', protected: true, source: 'dashboard_resumen', field: 'promedio_por_reclamo', aggregation: 'average', datasetScope: 'all' },
    { id: 'kpiComunaTop', title: 'Top reclamos', description: 'Comuna con mayor cantidad de reclamos.', icon: 'map', accent: 'amber', visible: true, order: 0, section: 'side', size: 'medium', protected: true, source: 'dashboard_comunas', field: 'reclamos', aggregation: 'max', datasetScope: 'all' },
    { id: 'kpiFacturacionTop', title: 'Top facturacion', description: 'Comuna con mayor facturacion.', icon: 'chart', accent: 'blue', visible: true, order: 1, section: 'side', size: 'medium', protected: true, source: 'dashboard_comunas', field: 'facturacion', aggregation: 'max', datasetScope: 'all' },
    { id: 'kpiCoberturaComunas', title: 'Cobertura', description: 'Comunas con informacion disponible.', icon: 'shield', accent: 'green', visible: true, order: 2, section: 'side', size: 'medium', protected: true, source: 'dashboard_comunas', field: 'comuna', aggregation: 'count', datasetScope: 'all' },
    { id: 'statTotalComunas', title: 'Total comunas', description: 'Cantidad de comunas filtradas.', icon: 'map', accent: 'blue', visible: true, order: 0, section: 'bottom', size: 'small', protected: true, source: 'dashboard_resumen', field: 'total_comunas', aggregation: 'sum', datasetScope: 'all' },
    { id: 'statAltaPrioridad', title: 'Alta prioridad', description: 'Reclamos de prioridad alta.', icon: 'alert', accent: 'red', visible: true, order: 1, section: 'bottom', size: 'small', protected: true, source: 'dashboard_resumen', field: 'alta_prioridad', aggregation: 'sum', datasetScope: 'all' },
    { id: 'statVariacionMensual', title: 'Periodo analizado', description: 'Periodo aplicado a datos actuales.', icon: 'chart', accent: 'slate', visible: true, order: 2, section: 'bottom', size: 'small', protected: true, source: 'dashboard_resumen', field: 'reclamos_totales', aggregation: 'count', datasetScope: 'all' },
    { id: 'statTicketsUnicos', title: 'Tickets unicos', description: 'Tickets distintos en el periodo.', icon: 'users', accent: 'cyan', visible: true, order: 3, section: 'bottom', size: 'small', protected: true, source: 'dashboard_resumen', field: 'tickets_unicos', aggregation: 'sum', datasetScope: 'all' },
  ],
  charts: [
    { id: 'chartGraficoFacturacionMensual', title: 'Facturacion mensual', subtitle: 'Evolucion mensual de facturacion.', type: 'line', source: 'dashboard_reclamos', xField: 'mes', yField: 'facturacion', aggregation: 'sum', datasetScope: 'all', visible: true, order: 0, section: 'bottom', size: 'medium', accent: 'blue', protected: true },
    { id: 'chartTopComunasReclamos', title: 'Top 10 comunas con mas reclamos', subtitle: 'Ranking por volumen de reclamos.', type: 'bar', source: 'dashboard_comunas', xField: 'comuna', yField: 'reclamos', aggregation: 'sum', datasetScope: 'all', visible: true, order: 1, section: 'bottom', size: 'medium', accent: 'red', protected: true },
    { id: 'chartTopComunasFacturacion', title: 'Top 10 comunas con mayor facturacion', subtitle: 'Ranking por facturacion.', type: 'bar', source: 'dashboard_comunas', xField: 'comuna', yField: 'facturacion', aggregation: 'sum', datasetScope: 'all', visible: true, order: 2, section: 'bottom', size: 'medium', accent: 'blue', protected: true },
    { id: 'chartDistribucionPrioridad', title: 'Distribucion por prioridad', subtitle: 'Composicion por prioridad.', type: 'pie', source: 'dashboard_reclamos', xField: 'prioridad', yField: 'ticket', aggregation: 'count', datasetScope: 'all', visible: true, order: 3, section: 'bottom', size: 'medium', accent: 'cyan', protected: true },
  ],
  components: [
    { id: 'header', title: 'Encabezado', subtitle: 'Titulo y subtitulo del dashboard', visible: true, order: 0, section: 'hero', size: 'full' },
    { id: 'filters', title: 'Filtros', subtitle: 'Barra de filtros operativos', visible: true, order: 1, section: 'hero', size: 'full' },
    { id: 'left-kpi-facturacion', title: 'Facturacion total', subtitle: 'Monto total del periodo', visible: true, order: 0, section: 'hero', size: 'medium', accent: 'blue' },
    { id: 'left-kpi-reclamos', title: 'Reclamos totales', subtitle: 'Total de reclamos filtrados', visible: true, order: 1, section: 'hero', size: 'medium', accent: 'red' },
    { id: 'left-kpi-promedio', title: 'Promedio por reclamo', subtitle: 'Facturacion promedio por reclamo', visible: true, order: 2, section: 'hero', size: 'medium', accent: 'cyan' },
    { id: 'main-map', title: 'Mapa de reclamos', subtitle: 'Intensidad territorial de reclamos', visible: true, order: 0, section: 'main', size: 'large', accent: 'blue' },
    { id: 'right-summary', title: 'Resumen operativo', subtitle: 'Top reclamos, facturacion y cobertura', visible: true, order: 0, section: 'side', size: 'medium' },
    { id: 'card-total-comunas', title: 'Total comunas', subtitle: 'Cantidad de comunas filtradas', visible: true, order: 0, section: 'bottom', size: 'small', accent: 'blue' },
    { id: 'card-alta-prioridad', title: 'Alta prioridad', subtitle: 'Reclamos de prioridad alta', visible: true, order: 1, section: 'bottom', size: 'small', accent: 'red' },
    { id: 'card-periodo', title: 'Periodo analizado', subtitle: 'Periodo aplicado a datos actuales', visible: true, order: 2, section: 'bottom', size: 'small', accent: 'slate' },
    { id: 'card-tickets', title: 'Tickets unicos', subtitle: 'Tickets distintos en el periodo', visible: true, order: 3, section: 'bottom', size: 'small', accent: 'cyan' },
    { id: 'chart-facturacion-mensual', title: 'Facturacion mensual', subtitle: 'Evolucion mensual de facturacion', visible: true, order: 4, section: 'bottom', size: 'medium', accent: 'blue' },
    { id: 'chart-top-reclamos', title: 'Top 10 comunas con mas reclamos', subtitle: 'Ranking por volumen de reclamos', visible: true, order: 5, section: 'bottom', size: 'medium', accent: 'red' },
    { id: 'chart-top-facturacion', title: 'Top 10 comunas con mayor facturacion', subtitle: 'Ranking por facturacion', visible: true, order: 6, section: 'bottom', size: 'medium', accent: 'blue' },
    { id: 'chart-prioridad', title: 'Distribucion por prioridad', subtitle: 'Composicion por prioridad', visible: true, order: 7, section: 'bottom', size: 'medium', accent: 'cyan' },
    { id: 'table-evidencia', title: 'Evidencia por comuna', subtitle: 'Tabla de respaldo operacional', visible: true, order: 8, section: 'bottom', size: 'large', accent: 'blue' },
    { id: 'route-visitador', title: 'Ruta Visitador', subtitle: 'Gestion de rutas de visita', visible: true, order: 9, section: 'bottom', size: 'medium' },
  ],
} as const satisfies DesignPreset;
